### ISSUE TITLE
Images in jupyter notebook are distorted

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#670] opened 2019-09-04 05:54 UTC
![image](https://user-images.githubusercontent.com/13106721/64228393-8c438a00-ce9b-11e9-8b26-5fc0a34b7701.png)

See https://github.com/QuantEcon/lecture-source-jl/blob/master/source/rst/getting_started_julia/getting_started.rst for example.  OS: Windows 10, browser:

**Comment by mmcky** [comment] 2019-09-04 05:57
hey @jlperla I don't see that on the live site for that lecture?
https://lectures.quantecon.org/jl/getting_started_julia/getting_started.html

**Comment by mmcky** [comment] 2019-09-04 05:57
ah - its in https://lectures.quantecon.org/jl/getting_started_julia/julia_environment.html

**Comment by jlperla** [comment] 2019-09-05 21:18
@arnavs  One thing to check out is whether it is hideous in both jupyter notebooks and jupyterlab.

**Comment by jlperla** [comment] 2019-09-05 21:20
I can confirm on windows+chrome that the notebooks accessed from jupyterlab are messed up, while the ones in jupyter notebook are good.  There may be some workaround needed for embedding images so that jupyterlab works?  Since it is now > 1.0, it will quickly become the standard.

**Comment by arnavs** [comment] 2019-09-05 23:44
in general, my gut is that the current HTML output is deferring to the browser on some sizing, instead of hard-coding it (cc @drdrij @mmcky)

and in some configurations the host machines are making bad choices? so if we could just box or bound these things somehow…

**Comment by mmcky** [comment] 2019-09-06 04:32
So this is a `jupyterlab` issue? My recommendation would be to edit a notebook in jupyterlab until you get the desired output and then let us know what the compatible `html` for images would be in that context.

**Comment by mmcky** [comment] 2019-09-06 06:39
just to confirm -- `jupyterlab` looks fine for me on `OS X` and `Chrome` -- so not sure what the cause for this is on windows. @jlperla is your chrome up to date on Windows by any chance?

**Comment by jlperla** [comment] 2019-09-07 04:07
> just to confirm -- jupyterlab looks fine for me on OS X and Chrome -- so not sure what the cause for this is on windows. @jlperla is your chrome up to date on Windows by any chance?

Yes.  But just to confirm, this is an old and recurring issue.  We had issues with it before, but I think we hacked it by just tweaking the scale (if I recall).  @arnavs  do you remember?  It is very possible that this lecture never looked good on windows chrome with jupyterlab

The reason it is coming to a head now is that: jupyterlab is released, so it is a reasonable default.  We edited the lecture notes to tell people to use it.

ALso, I can't remember if I told you guys, but changing
```html
<img src="https://s3-ap-southeast-2.amazonaws.com/lectures.quantecon.org/jl/_static/figures/nb3_julia.png" style="width:100%;height:100%">
```
To something like
```html
<img src="https://s3-ap-southeast-2.amazonaws.com/lectures.quantecon.org/jl/_static/figures/nb3_julia.png" style="width:100%;height:auto">
```
Fixes the problem completely.  Could we have a version of the rst code for including notebooks that takes
```
.. figure:: /_static/figures/starting_nb_julia.png
   :scale: 100%
```

And instead goes
```
.. figure:: /_static/figures/starting_nb_julia.png
   :width: 100%
```
Or, alternatively, what if the `:scale:` just changes the `width` CSS attribute and leaves the height as `auto`?

**Comment by arnavs** [comment] 2019-09-09 00:12
Yeah, we fixed this in a hacky by using the `:scale:` directive or something. 

@jlperla That is very useful information. 

@AakashGfude See above. Basically, the distortion is one direction (`height`), and the problem disappears if we set that to `auto` instead of `100%` along with the scale. I think it's now a raw Jupinx problem (i.e., what `style` metadata are we associating with image RST?)

**Comment by mmcky** [comment] 2019-09-09 01:32
thanks @jlperla @arnavs. The `html` code is super helpful. We can certainly change the way `html` links are written to the notebook to use `auto`. @AakashGfude can you take a look at the `html` and let me know what is the most `web` compliant way to build these scale parameters. Is there a compatibility checker for browsers out there?

**Comment by AakashGfude** [comment] 2019-09-10 01:44
`height:auto` and `width:percentage` seems to be a good web compliant way to do this, unless we want full control of how height is scaled.  
If height: auto; the element will automatically adjust its height to allow its content to be displayed correctly.  So, good enough for us. 
Have adjusted this property of `scale` to leave height as `auto` in this [branch](https://github.com/QuantEcon/sphinxcontrib-jupyter/tree/image-scale) for testing.
Thanks @jlperla @arnavs @mmcky

**Comment by mmcky** [comment] 2019-09-10 02:02
@AakashGfude out of interested how does `sphinx` `html` writer handle `:scale:`

**Comment by AakashGfude** [comment] 2019-09-10 02:08
@mmcky it handles it the same way as was implemented by us before :- adjusts both the `height` and `width` percentages. it is implemented in docutils though - http://docutils.sourceforge.net/docs/ref/rst/directives.html#image

**Comment by mmcky** [comment] 2019-09-10 02:10
thanks @AakashGfude. My only concern with adding `auto` is it technically will no longer be a `:scale:` setting but rather essentially a width setting. Perhaps we should just change the `RST` to use `:width:` rather than `:scale:`?

**Comment by AakashGfude** [comment] 2019-09-10 02:19
@mmcky you are right. `height:auto` turns out to be a default setting anyways. The only advantage of having explicit `height:auto` is to override any style which might have been propagated from some class or file.

**Comment by mmcky** [comment] 2019-09-10 02:24
@jlperla perhaps we can update the RST to use the `:width:` scaling option as that is your preferred setting? FYI - On the `py` side we have gotten rid of most `:scale:` calls in favour of having natively sized `static` files as sources that don't required resizing.

**Comment by arnavs** [comment] 2019-09-13 17:40
Closing this since I think switching over to the `:width:` directive did the trick.

**Closed by arnavs** 2019-09-13 17:40 UTC
Labels: high-priority, wait-and-see
