### ISSUE TITLE
Error with instantiatefromurl on vse.syzygy.ca

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#668] opened 2019-09-04 05:35 UTC
![image](https://user-images.githubusercontent.com/13106721/64228254-18a17d00-ce9b-11e9-880c-2ea3846a762f.png)

**Comment by arnavs** [comment] 2019-09-04 06:41
@jlperla Closing because I can't reproduce. 

This is a Linux error (not Julia) that probably is coming from the changes I made to (e.g.) nuke your `.julia` directory, and things like that. 

<img width="1117" alt="Screen Shot 2019-09-03 at 11 41 08 PM" src="https://user-images.githubusercontent.com/5009477/64231368-50f98900-cea4-11e9-9595-c16d83bd1c63.png">

**Comment by arnavs** [comment] 2019-09-04 06:41
(So, if we restart your server, maybe with one more round of nuking, you should be OK.)

**Closed by arnavs** 2019-09-04 06:41 UTC

**Comment by jlperla** [comment] 2019-09-04 13:02
Yup, your fix worked.  I think we will want to have a script that does the nuking/server stopping for everyone when we need to.
