### ISSUE TITLE
Downloaded jupyter notebook from http://compare-lectures.quantecon.org/jl/generic_programming.html#  is not the same as HTML 

### ISSUE THREAD

**Issue by PooyaFa** [QuantEcon/lecture-source-jl#378] opened 2018-11-20 00:21 UTC
This is the reason that in the setup section versions are different (0.9.0 vs 0.1.2)

**Comment by arnavs** [comment] 2018-11-20 00:35
@PooyaFa I'm going to close this, since as Jesse pointed out this is a duplicate of https://github.com/QuantEcon/lecture-source-jl/issues/323

**Closed by arnavs** 2018-11-20 00:35 UTC
