### ISSUE TITLE
Remove the PDF badge for now

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#649] opened 2019-08-29 23:29 UTC
cc: @mmcky

**Comment by arnavs** [comment] 2019-09-01 21:56
Made the relevant change to `julia.tpl`; should be reflected in the next clean build.

**Comment by arnavs** [comment] 2019-09-02 05:44
Closing since I confirmed this is gone in the latest `preview-lectures` build.

**Closed by arnavs** 2019-09-02 05:44 UTC
Labels: awaiting-testing
