### ISSUE TITLE
Regression testing for the julia lectures in the "builds"

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#303] opened 2018-11-13 17:52 UTC
cc: @mmcky @arnavs 

Looking at the http://compare-lectures.quantecon.org/status.html  I notice a few things:
* It says that it is running all sorts of tests, including for some of the new lectures?
* It still says "julia 0.6"

Is this up and running?  If so, we should verify that it is behaving as we expect:
* It is running the version of the lectures with the tests enabled, as opposed to the HTML and notebook generation, which should have the regression tests stripped out.
* Change the text to Julia 1.0 if appropriate

**Comment by arnavs** [comment] 2018-12-11 20:34
Closing because the execution status now incorporates regression tests.

**Closed by arnavs** 2018-12-11 20:34 UTC
Labels: build-infrastructure
